/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-05-12 11:06:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Pages.vinde;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class configuraremodel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Resurse/demo.css\"/>\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Resurse/ttlogo.png\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Resurse/easydropdown.css\"/>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Resurse/finalizeazaButton.css\">\r\n");
      out.write("\t\t<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css'>\r\n");
      out.write("\t\t<script src=\"https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js\"></script>\r\n");
      out.write("\t\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Resurse/jquery.easydropdown.js\"></script>\r\n");
      out.write("<title>TodayTech</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".pretcss{\r\n");
      out.write("\tmargin-top:-2%;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    line-height: 1;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    \r\n");
      out.write("    padding: 9px 12px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write(".buttonContinua {\r\n");
      out.write("\tfont-family: 'CopenhagenGroteskNova', -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("    margin-right: auto;\r\n");
      out.write("    \r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbox-shadow: 0px 0px 17px 4px #fafafa;\r\n");
      out.write("\tbackground-color:#f26422;\r\n");
      out.write("\tborder-radius:4px;\r\n");
      out.write("\tborder:1px solid #f26422;\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\tcolor:#ffffff;\r\n");
      out.write("\tfont-size:1.3rem;\r\n");
      out.write("\tmargin-top:2%;\r\n");
      out.write("\tfont-weight:500;\r\n");
      out.write("\tpadding:.875rem 1rem;\r\n");
      out.write("\tbox-sizing: content-box;\r\n");
      out.write("}\r\n");
      out.write(".buttonContinua:hover {\r\n");
      out.write("\tbackground-color:#f26422;\r\n");
      out.write("}\r\n");
      out.write(".buttonContinua:active {\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1{\r\n");
      out.write("    font-family: \"Avenir Next\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\r\n");
      out.write("    color: #353b50;\r\n");
      out.write("    letter-spacing: 0;\r\n");
      out.write("    line-height: 1.2;\r\n");
      out.write("    font-size: 2.15rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".bara{\r\n");
      out.write("\tbackground: #f26522;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    -webkit-animation-duration: 1s;\r\n");
      out.write("    animation-duration: 1s;\r\n");
      out.write("    -webkit-animation-fill-mode: both;\r\n");
      out.write("    animation-fill-mode: both;\r\n");
      out.write("    -webkit-animation-name: slideInLeft;\r\n");
      out.write("    animation-name: slideInLeft;\r\n");
      out.write("}\r\n");
      out.write(".middle{\r\n");
      out.write("\tmargin-left:auto;\r\n");
      out.write("\tmargin-right:auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".bara-fundal {\r\n");
      out.write("    background: #D2D8E3;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    height: 5px;\r\n");
      out.write("    width: 60%;\r\n");
      out.write("    margin:0 auto;\r\n");
      out.write("    margin-top:5%;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    transition: all .2s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".configurare{\r\n");
      out.write("\tmargin-left:auto;\r\n");
      out.write("\tmargin-right:auto;\r\n");
      out.write("\tmargin-top:2%;\r\n");
      out.write("\twidth:50%;\r\n");
      out.write("\theight:70%;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".divsus{\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    z-index: 1030;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height: 4rem;\r\n");
      out.write("    margin:0;\r\n");
      out.write("}\r\n");
      out.write("h3{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("    font-size: 1.17em;\r\n");
      out.write("    margin-block-start: 1em;\r\n");
      out.write("    margin-block-end: 1em;\r\n");
      out.write("    margin-inline-start: 0px;\r\n");
      out.write("    margin-inline-end: 0px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    letter-spacing: 0.04px;\r\n");
      out.write("    color: #353b50;\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    margin-bottom: 1.25rem;\r\n");
      out.write("}\r\n");
      out.write("@keyframes slideInLeft {\r\n");
      out.write("  0% {\r\n");
      out.write("    transform: translate3d(-100%, 0, 0);\r\n");
      out.write("    visibility: visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("100% {\r\n");
      out.write("    transform: translateZ(0);\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\tconst queryString = window.location.search;\r\n");
      out.write("\t\tconst urlParams = new URLSearchParams(queryString);\r\n");
      out.write("\t\tconst email = urlParams.get('email');\r\n");
      out.write("\t\tvar a=\"\"\r\n");
      out.write("\t\tfor(var i=0;i<document.getElementsByTagName(\"form\").length;i++){\r\n");
      out.write("\t\t\tvar a=(document.getElementsByTagName(\"form\")[i].action+email).substring((document.getElementsByTagName(\"form\")[i].action+email).indexOf(\"/todaytech/\"));\r\n");
      out.write("\t\t\tdocument.getElementsByTagName(\"form\")[i].setAttribute(\"action\", a); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction setPret()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar s=\"\";\r\n");
      out.write("\t\tif(form.cond[form.cond.selectedIndex].text.localeCompare(\"Ca nou\")==0)\r\n");
      out.write("\t\t\ts=\"2500\";\r\n");
      out.write("\t\telse if(form.cond[form.cond.selectedIndex].text.localeCompare(\"Excelent\")==0)\r\n");
      out.write("\t\t\ts=\"2200\";\r\n");
      out.write("\t\telse if(form.cond[form.cond.selectedIndex].text.localeCompare(\"Foarte bun\")==0)\r\n");
      out.write("\t\t\ts=\"1900\";\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\ts=\"1600\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar m=1;\r\n");
      out.write("\t\tif(form.cond[form.cond.selectedIndex].text==\"Conditia telefonului\" || form.mem_int[form.mem_int.selectedIndex].text==\"Memorie interna\" || form.retea[form.retea.selectedIndex].text==\"Retea\" || form.culoare[form.culoare.selectedIndex].text==\"Culoare\")\r\n");
      out.write("\t\t\tm=0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(m==0){\r\n");
      out.write("\t\t\tvar x = document.getElementById(\"container\");\r\n");
      out.write("\t\t\tx.style.display = \"none\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar x = document.getElementById(\"container\");\r\n");
      out.write("\t\t\tx.style.display = \"block\";\r\n");
      out.write("\t\t\tdocument.getElementById('pret').innerHTML=(\"Pret: \"+s+\" lei\");\r\n");
      out.write("\t\t\tvar a=\"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i=0;i<document.getElementsByTagName(\"form\").length;i++){\r\n");
      out.write("\t\t\t\tvar a=(document.getElementsByTagName(\"form\")[i].action+\"&pret=\"+s).substring((document.getElementsByTagName(\"form\")[i].action+\"&pret=\"+s).indexOf(\"/todaytech/\"));\r\n");
      out.write("\t\t\t\tdocument.getElementsByTagName(\"form\")[i].setAttribute(\"action\", a); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"divsus\"></div>\r\n");
      out.write("<div class=\"bara-fundal\"><span class=\"bara\" style=\"width: 60%;\"></span></div>\r\n");
      out.write("<h1 style=\"font-size:50px;text-align:center;margin-top:3%\">Configureaza ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("<div class=\"configurare\">\r\n");
      out.write("<form id=\"form\" class=\"form\" name=\"form\" method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vindeFinalizare?model=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${model}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("  <select tabindex=\"4\" name=\"culoare\" onchange=\"setPret()\" class=\"dropdown\" data-settings='{\"cutOff\": 4}'>\r\n");
      out.write("    <option value=\"Culoare\" class=\"label\">Culoare</option>\r\n");
      out.write("    <option value=\"Rosu\" class=\"label\">Rosu</option>\r\n");
      out.write("    <option value=\"Alb\">Alb</option>\r\n");
      out.write("    <option value=\"Negru\">Negru</option>\r\n");
      out.write("    <option value=\"Gri\">Gri</option>\r\n");
      out.write("  </select>\r\n");
      out.write("  <select tabindex=\"4\" name=\"mem_int\" onchange=\"setPret()\" class=\"dropdown\" data-settings='{\"cutOff\": 4}'>\r\n");
      out.write("    <option value=\"Memorie interna\" class=\"label\">Memorie interna</option>\r\n");
      out.write("    <option value=\"64GB\" class=\"label\">64GB</option>\r\n");
      out.write("    <option value=\"128GB\">128GB</option>\r\n");
      out.write("    <option value=\"256GB\">256GB</option>\r\n");
      out.write("    <option value=\"512GB\">512GB</option>\r\n");
      out.write("  </select>\r\n");
      out.write("  <select tabindex=\"4\" onchange=\"setPret()\" name=\"retea\" class=\"dropdown\" data-settings='{\"cutOff\": 4}'>\r\n");
      out.write("    <option value=\"Reteaua\" class=\"label\">Retea</option>\r\n");
      out.write("    <option value=\"Deblocat\" class=\"label\">Deblocat</option>\r\n");
      out.write("    <option value=\"Orange\">Orange</option>\r\n");
      out.write("    <option value=\"Vodafone\">Vodafone</option>\r\n");
      out.write("    <option value=\"Digi\">Digi</option>\r\n");
      out.write("  </select>\r\n");
      out.write("  <select tabindex=\"4\" name=\"cond\" onchange=\"setPret()\" class=\"dropdown\" data-settings='{\"cutOff\": 4}'>\r\n");
      out.write("    <option value=\"Conditia telefonului\" class=\"label\">Conditia telefonului</option>\r\n");
      out.write("    <option value=\"Ca_nou\">Ca nou</option>\r\n");
      out.write("    <option value=\"Excelent\">Excelent</option>\r\n");
      out.write("    <option value=\"Foarte_bun\">Foarte bun</option>\r\n");
      out.write("    <option value=\"Bun\">Bun</option>\r\n");
      out.write("  </select>\r\n");
      out.write("  <label class=\"pretcss\" name=\"pret\" id=\"pret\">&nbsp</label>\r\n");
      out.write("  <img style=\"margin-left:auto;margin-right:auto;max-width: 30rem;height: 30rem;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Resurse/PozeTelefoane/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${poza}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"symbol image\">\r\n");
      out.write("  <br>\r\n");
      out.write("  <div id=\"container\" style=\"margin-top:2%;display:none\">\r\n");
      out.write("  <button class=\"learn-more\">\r\n");
      out.write("    <span class=\"circle\" aria-hidden=\"true\">\r\n");
      out.write("      <span class=\"icon arrow\"></span>\r\n");
      out.write("    </span>\r\n");
      out.write("    <span class=\"button-text\">Finalizeaza</span>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
